---
title: "IntelemonAnalysis"
author: "Christina Fossum"
date: "2025-04-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Step 1: Load Data

Save intelimon download folder in TLS folder in TLS Repository. Unzip all files (Go into CORMP -> YEAR -> unzip these too!)
```{r}
#Load Packages
library(tidyverse)
library(dplyr)
library(writexl)
library(knitr)
library(EnvStats)



###Load README file
readme <- read.csv("IntELiMon_u5cbQBufr9udP9MdninK/IntELiMon_output_readme.csv")

###Load Table Descriptions
key <- read.csv("IntELiMon_u5cbQBufr9udP9MdninK/IntELiMon_metrics_table_descriptions.csv")

###Load metrics data
metrics <- read.csv("IntELiMon_u5cbQBufr9udP9MdninK/merged_metrics.csv")

###Load inventory data
#Set Directory Path
directory_path <- "IntELiMon_u5cbQBufr9udP9MdninK/CORMP/2024/"

#Create function to load individual data files into single dataframe
load_data <- function(directory_path, pattern) {
  list_files <- list.files(path = directory_path, pattern = pattern, full.names = TRUE, recursive = TRUE)
  data_list <- lapply(list_files, function(file) {
    file_data <- read.csv(file) 
    file_data <- file_data %>% mutate(FileName = basename(file))
  })
  return(do.call(rbind, data_list))
}

#Load inventory dataframe 
inv <- load_data(directory_path, "_inv.csv$")

###Load Shrubs data frame
shrubs <- load_data(directory_path, "_2.csv$")








```
