---
title: "PicoModels"
author: "Christina Fossum"
date: "2026-01-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# PICO Models from TLS scans
Edited by: Christina Fossum 1/19/2026

Contents
1. Snag Basal Area


1. basal area
```{r}
library(tidyverse)
library(leaps)
library(performance)
library(ggplot2)

#Load data
pred <- read.csv("pico_ap_pred.csv")
vars <- read.csv("pico_ap_vars.csv")

pred <- pred %>% select(-1)
vars <- vars %>% select(-1)

vars <- vars %>% mutate(across(where(is.character), as.factor)) %>% select(where(~!is.factor(.) || nlevels(.) > 1)) %>% select(where(~sum(is.na(.)) == 0))

## Split data into training and test datasets
set.seed(123)
sample_size <- floor(0.2 * nrow(vars))
test_indices <- sample(seq_len(nrow(vars)), size = sample_size)
train_vars <- vars[-test_indices, ]
test_vars <- vars[test_indices, ]
train_pred <- pred[-test_indices, ]
test_pred <- pred[test_indices, ]

#Set method to 'seqrep', nvmax to '4' and variable to 'TreesPerAcre'
regfit = regsubsets(train_pred$ba_ft2_peracre~., train_vars,  nvmax = 3 , method = "seqrep", really.big = T) 

# Check models (***Question: seems to always be 4, is this step really necessary? I'm not totaly sure what I am looking for)
regsum<- summary(regfit)
plot(regsum$rsq, type = "l") 
plot(regsum$rss, type = "l") 
plot(regsum$bic, type = "l") 
which.min(regsum$bic) 
plot(regfit, scale = "r2") 

#Change # to best model
vcov(regfit,3) 
coef(regfit,3)

attach(train_vars)

# put the selected predictor variables in the model after the "~" seperated by "+" and run the model
lm1 <- lm(formula = train_pred$ba_ft2_peracre~ h_l4_std + s_l5_prop_sd  +  vox_l1_cnt)


#look at the summary r2 values and RMSE
#***Are there specific r2 and rmse values I am looking for here??
summary(lm1)
r2(lm1)
rmse(lm1)

# Visual check of model assumptions. Make sure Linearity, homogeneity of variance, influential observations, colinearity, normality of risiduals all check out
check_model(lm1)

#use the model to predict out new values from variables alone
lm_out <- predict.lm(lm1, vars)


#format the predictions and observations for plotting
data<-data.frame(x=lm_out, y=pred$ba_ft2_peracre)

# Plot observed values vs. predicted
ggplot(data,aes(x,y)) +
  geom_point() +
  geom_smooth(method='lm', se=FALSE,) +
  theme_light() +
  labs(x='Predicted Values', y='Observed Values', title='?') +
  theme(plot.title = element_text(hjust=0.5, size=20, face='bold') 
  ) 

# use the model to predict test data
test_out<- predict.lm(lm1,test_vars)

# Calculate RMSE of test data
errors<- test_out - test_pred$ba_ft2_peracre
mae <- mean(abs(errors))
mse <- mean(errors^2)
rmse <- sqrt(mse)
rmse

# format test predicted and observed
data2<- data.frame(x=test_out, y=test_pred$ba_ft2_peracre)

# Plot test observed values vs. test predicted
ggplot(data2,aes(x,y)) +
  geom_point() +
  geom_smooth(method='lm', se=FALSE,) +
  theme_light() +
  labs(x='Predicted Values', y='Observed Values', title='test') +
  theme(plot.title = element_text(hjust=0.5, size=20, face='bold') 
  ) 


# If the model looks good, save to disk
saveRDS(lm1,  "picoAP_Basal_Area.rda") 

```

2. Live Trees per acre
```{r}
library(tidyverse)
library(leaps)
library(performance)
library(ggplot2)

#Load data
pred <- read.csv("pico_ap_pred.csv")
vars <- read.csv("pico_ap_vars.csv")

pred <- pred %>% select(-1)
vars <- vars %>% select(-1)

vars <- vars %>% mutate(across(where(is.character), as.factor)) %>% select(where(~!is.factor(.) || nlevels(.) > 1)) %>% select(where(~sum(is.na(.)) == 0))

## Split data into training and test datasets
set.seed(123)
sample_size <- floor(0.2 * nrow(vars))
test_indices <- sample(seq_len(nrow(vars)), size = sample_size)
train_vars <- vars[-test_indices, ]
test_vars <- vars[test_indices, ]
train_pred <- pred[-test_indices, ]
test_pred <- pred[test_indices, ]

#Set method to 'seqrep', nvmax to '4' and variable to 'TreesPerAcre'
regfit = regsubsets(train_pred$DTrees_perAcre~., train_vars,  nvmax = 3 , method = "seqrep", really.big = T) 

# Check models (***Question: seems to always be 4, is this step really necessary? I'm not totaly sure what I am looking for)
regsum<- summary(regfit)
plot(regsum$rsq, type = "l") 
plot(regsum$rss, type = "l") 
plot(regsum$bic, type = "l") 
which.min(regsum$bic) 
plot(regfit, scale = "r2") 

#Change # to best model
vcov(regfit,3) 
coef(regfit,3)

attach(train_vars)

# put the selected predictor variables in the model after the "~" seperated by "+" and run the model
lm1 <- lm(formula = train_pred$DTrees_perAcre~ h_l3_vari   +  h_GC_mean  + fine_l1_cnt)


#look at the summary r2 values and RMSE
#***Are there specific r2 and rmse values I am looking for here??
summary(lm1)
r2(lm1)
rmse(lm1)

# Visual check of model assumptions. Make sure Linearity, homogeneity of variance, influential observations, colinearity, normality of risiduals all check out
check_model(lm1)

#use the model to predict out new values from variables alone
lm_out <- predict.lm(lm1, vars)


#format the predictions and observations for plotting
data<-data.frame(x=lm_out, y=pred$DTrees_perAcre)

# Plot observed values vs. predicted
ggplot(data,aes(x,y)) +
  geom_point() +
  geom_smooth(method='lm', se=FALSE,) +
  theme_light() +
  labs(x='Predicted Values', y='Observed Values', title='?') +
  theme(plot.title = element_text(hjust=0.5, size=20, face='bold') 
  ) 

# use the model to predict test data
test_out<- predict.lm(lm1,test_vars)

# Calculate RMSE of test data
errors<- test_out - test_pred$LTrees_perAcre
mae <- mean(abs(errors))
mse <- mean(errors^2)
rmse <- sqrt(mse)
rmse

# format test predicted and observed
data2<- data.frame(x=test_out, y=test_pred$LTrees_perAcre)

# Plot test observed values vs. test predicted
ggplot(data2,aes(x,y)) +
  geom_point() +
  geom_smooth(method='lm', se=FALSE,) +
  theme_light() +
  labs(x='Predicted Values', y='Observed Values', title='test') +
  theme(plot.title = element_text(hjust=0.5, size=20, face='bold') 
  ) 


# If the model looks good, save to disk
saveRDS(lm1,  "picoAP_LTreesperacre.rda") 

```


3. D, L, OS, Pole
```{r}
library(tidyverse)
library(leaps)
library(performance)
library(ggplot2)

#Load data
pred <- read.csv("pred.csv")
vars <- read.csv("vars.csv")

pred <- read.csv("pico_ap_pred.csv")
vars <- read.csv("pico_ap_vars.csv")

pred <- pred %>% select(-1)
vars <- vars %>% select(-1)

vars <- vars %>% mutate(across(where(is.character), as.factor)) %>% select(where(~!is.factor(.) || nlevels(.) > 1)) %>% select(where(~sum(is.na(.)) == 0))

## Split data into training and test datasets
set.seed(123)
sample_size <- floor(0.2 * nrow(vars))
test_indices <- sample(seq_len(nrow(vars)), size = sample_size)
train_vars <- vars[-test_indices, ]
test_vars <- vars[test_indices, ]
train_pred <- pred[-test_indices, ]
test_pred <- pred[test_indices, ]

#Set method to 'seqrep', nvmax to '4' and variable to 'TreesPerAcre'
regfit = regsubsets(train_pred$L~., train_vars,  nvmax = 3 , method = "seqrep", really.big = T) 

# Check models (***Question: seems to always be 4, is this step really necessary? I'm not totaly sure what I am looking for)
regsum<- summary(regfit)
plot(regsum$rsq, type = "l") 
plot(regsum$rss, type = "l") 
plot(regsum$bic, type = "l") 
which.min(regsum$bic) 
plot(regfit, scale = "r2") 

#Change # to best model
vcov(regfit,2) 
coef(regfit,2)

attach(train_vars)

# put the selected predictor variables in the model after the "~" seperated by "+" and run the model
lm1 <- lm(formula = train_pred$L~ h_GC_std +hr0_10_l1_median)


#look at the summary r2 values and RMSE
#***Are there specific r2 and rmse values I am looking for here??
summary(lm1)
r2(lm1)
rmse(lm1)

# Visual check of model assumptions. Make sure Linearity, homogeneity of variance, influential observations, colinearity, normality of risiduals all check out
check_model(lm1)

#use the model to predict out new values from variables alone
lm_out <- predict.lm(lm1, vars)


#format the predictions and observations for plotting
data<-data.frame(x=lm_out, y=pred$DTrees_perAcre)

# Plot observed values vs. predicted
ggplot(data,aes(x,y)) +
  geom_point() +
  geom_smooth(method='lm', se=FALSE,) +
  theme_light() +
  labs(x='Predicted Values', y='Observed Values', title='?') +
  theme(plot.title = element_text(hjust=0.5, size=20, face='bold') 
  ) 

# use the model to predict test data
test_out<- predict.lm(lm1,test_vars)

# Calculate RMSE of test data
errors<- test_out - test_pred$L
mae <- mean(abs(errors))
mse <- mean(errors^2)
rmse <- sqrt(mse)
rmse

# format test predicted and observed
data2<- data.frame(x=test_out, y=test_pred$Poles_perAcre)

# Plot test observed values vs. test predicted
ggplot(data2,aes(x,y)) +
  geom_point() +
  geom_smooth(method='lm', se=FALSE,) +
  theme_light() +
  labs(x='Predicted Values', y='Observed Values', title='test') +
  theme(plot.title = element_text(hjust=0.5, size=20, face='bold') 
  ) 


# If the model looks good, save to disk
saveRDS(lm1,  "picoAP_LTreesperacre.rda") 

```

